Hw 03 spring
ivlytvynets/spring-test pull request #3
Opened 2021-02-10 13:39 UTC by ivlytvynets

2021-02-10 15:40 UTC, Likh-Alex approved these changes

2021-02-10 15:40 UTC, Likh-Alex commented on pom.xml
> +        </dependency>
we can delete jsp dependencies as we are passing json to the page, take a look in the checklist

2021-02-11 08:25 UTC, Sofasmile requested changes

2021-02-11 08:25 UTC, Sofasmile commented on src/main/java/com/dev/lytvynets/dto/UserResponseDto.java
> +    private String firstName;
let's add id here too

2021-02-11 08:25 UTC, Sofasmile commented on src/main/java/com/dev/lytvynets/service/UserService.java
> +    Optional<User> get(Long id);
```suggestion
    User get(Long id);
```

2021-02-11 08:25 UTC, Sofasmile commented on src/main/java/com/dev/lytvynets/service/impl/UserMapperImpl.java
> +    public User getUserEntity(UserResponseDto userResponseDto) {
where do we use this method? Let's remove it)

2021-02-11 09:07 UTC, Sofasmile approved these changes

2021-02-11 09:13 UTC, merged